require('dotenv').config()

export const {
  DB_HOST,

  DB_DATABASE_INBOUND,
  DB_USER_INBOUND,
  DB_PASSWORD_INBOUND,

  DB_DATABASE_INNER,
  DB_USER_INNER,
  DB_PASSWORD_INNER,

  DB_DATABASE_LINE_RSS,
  DB_USER_LINE_RSS,
  DB_PASSWORD_LINE_RSS,

  NODE_ENV,
  AIRTABLE_API_KEY,
} = process.env
